services:
  - type: web
    name: mysql-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    disk:
      name: mysql_data
      sizeGB: 40 # Ajusta el tamaño según lo necesites
    healthCheckPath: /
    port: 3307
